language: python
dist: xenial
python:
- '2.4'
- '2.5'
- '2.6'
- '2.7'
- '3.0'
- '3.1'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 3.8-dev
script:
- echo "skipping tests"
deploy:
  provider: pypi
  user: DomDF
  on:
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: uGWIpVzbpd8gdnKaykZJArrVpIQ3+/b/RDM70hvYmgSBsOFR56NjslSgox4+X1AaPcGSorUgH2+2ZpsiKmgz/VLXdAFIOmv983plYhQpOn6FUjn2W7n/boGFaeiodRcf4ZT8DvdkRRU5dbBc8fKW+ACtbwgKZ0qLTfwIHf4R5OYebwFoH3PYg8ORhe5lxh0khytJthBJAv5pKzV97cwSW1my2NU6M8yVT7zsAoeexX42+/d5eVgteio+89SeVXu/SwqmdIn055zQkPm6aVFlIlpGonEpPTWRM98EZZPa7sTRQH116YJ95JN8xNd4kkK1JmdU17GJyYik/xJ1PoCBvBofqySw2eDhfl54vBVXZwOWgjMhS/v/2YsgoAi5pNkGqiDVinmpXZo2vRzN8PTpyoSVGLBNzxlSMl0lOMTzsy7RaQGoufVlW/IJUrX3rDMGoTdXnxLg18BL2gOXhjxxA38zCl3SUTw9Z0uuLGaOAbninfcYZ3Ac/r/SjkeVdAq3DvXgXIKUGYOdAjziASHdcvjM8RxarukYzyq7azKi5PWfHg+UchV4X4nNbZBe5wjSm4zBYEU/8jsIPkbI/GnRmxFRQzSSkauNnl/aidSN2/NdkMtyjhULyYNLz7lQvee0pVI1xWeZFkYtiNDcuyB3ywB37Q0v70kchT3XJMDpsVE=
